#!/usr/bin/env bash
# setup-mac.sh — one-shot pipestream bring-up for a memory-constrained box
# (e.g. a 24 GB Mac doing remote dev). Asks where to install (default ~/work),
# points the bootstrap there instead of /work, clones + builds the repos, seeds
# ~/.pipeline, then runs configure-external.sh to aim services at remote infra.
#
# Run from a checkout of dev-assets:
#   scripts/setup-mac.sh
set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ORG="ai-pipestream"
bold(){ printf '\n\033[1m%s\033[0m\n' "$1"; }
ask(){ local v="$1" p="$2" d="$3" in; printf '%s [%s]: ' "$p" "$d" >&2; read -r in; printf -v "$v" '%s' "${in:-$d}"; }
expand(){ printf '%s' "${1/#\~/$HOME}"; }

bold "== pipestream setup (memory-lean / remote-infra profile) =="
ask ROOT "Where should the builds be installed (workspace root)?" "$HOME/work"; ROOT="$(expand "$ROOT")"
ask M2   "Maven local repository (default avoids a settings.xml redirect)" "$HOME/.m2/repository"; M2="$(expand "$M2")"
echo "  -> repos go to: $ROOT/main/{core-services,modules,connectors,...}"
echo "  -> maven local: $M2"

# 1) per-machine override so bootstrap targets $ROOT and publishes to $M2.
#    Only [workspace] is overridden; the repo manifest is inherited.
CFG="${XDG_CONFIG_HOME:-$HOME/.config}/ai-pipestream"; mkdir -p "$CFG"
cat > "$CFG/workspace.toml" <<EOF
# Per-machine override generated by setup-mac.sh — edit freely.
[workspace]
root = "$ROOT"
m2_repo = "$M2"
EOF
bold "wrote override: $CFG/workspace.toml"

# 2) make sure dev-assets exists at the target to run the bootstrap from.
DA="$ROOT/main/dev-tools/dev-assets"
if [ ! -d "$DA/.git" ]; then
  bold "cloning dev-assets -> $DA"; mkdir -p "$(dirname "$DA")"
  git clone "https://github.com/$ORG/dev-assets.git" "$DA" || { echo "dev-assets clone failed"; exit 1; }
fi

# 3) bootstrap phases. `check` offers to install any missing prereqs
#    (Docker Desktop, sdkman+JDK, quarkus-cli, node/bun, process-compose).
cd "$DA"
bold "== prereqs =="            ; ./bootstrap.sh check || { echo "resolve prereqs, then re-run"; exit 1; }
bold "== clone all repos =="    ; ./bootstrap.sh clone || exit 1
bold "== build (seeds maven local) ==" ; ./bootstrap.sh build || exit 1
bold "== seed ~/.pipeline =="   ; ./bootstrap.sh seed  || exit 1

# 4) external endpoints (writes the delimited block into ~/.pipeline/dev/.env).
EXT="$DA/scripts/configure-external.sh"; [ -f "$EXT" ] || EXT="$SCRIPT_DIR/configure-external.sh"
if [ -f "$EXT" ]; then bold "== external endpoints =="; bash "$EXT"
else echo "!! configure-external.sh not found — run scripts/configure-external.sh manually."; fi

bold "Done. To bring it up:"
echo "  cp $DA/scripts/templates/compose-devservices.override.lean.yml ~/.pipeline/compose-devservices.override.yml"
echo "  dev-services up"
echo "  process-compose -f ~/.pipeline/dev/process-compose.yaml up"
